leftnav:
- identifier: c9b2c0ce-848b-e884-986d-2c96a98e68a0
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 0cb6be5f-80d8-734a-81be-2b744d43f9be
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 2c369a02-9f64-7495-c2b3-4194036a2626
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 30
- identifier: 3a17781a-68d0-f2c3-fd7b-c85d68f577b8
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
- identifier: 70ca0fa4-a93b-e58d-e7bb-104525341a9d
  name: Projects
  pageRef: /pages/projects
  weight: 50
